const icon = (slug) => `https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/${slug}.svg`;

export const demoCategories = [
  { id: 1, name: 'Entertainment', slug: 'entertainment', description: 'Streaming, video and entertainment apps.', glyph: '▶' },
  { id: 2, name: 'Tools', slug: 'tools', description: 'Useful Android utilities and productivity tools.', glyph: '✦' },
  { id: 3, name: 'Games', slug: 'games', description: 'Popular Android games and gaming platforms.', glyph: '◆' },
  { id: 4, name: 'Photography', slug: 'photography', description: 'Photo, video and creative editing apps.', glyph: '◉' },
  { id: 5, name: 'Music', slug: 'music', description: 'Music, podcasts and audio discovery apps.', glyph: '♫' },
  { id: 6, name: 'Communication', slug: 'communication', description: 'Messaging, communities and communication apps.', glyph: '✉' },
  { id: 7, name: 'Social', slug: 'social', description: 'Social networks and content communities.', glyph: '◎' }
];

const commonContent = (name) => `<h2>About ${name}</h2><p>This is a visual demo listing used to preview the APKMarket design. Replace the content, download URL and files from the CMS with software you are authorised to publish.</p><h2>What you can manage</h2><p>From the CMS you can edit headings, paragraphs, images, tables, specifications, feature lists, SEO metadata and structured data for every app.</p>`;

export const demoApps = [
  {id:1,title:'Spotify',slug:'spotify',short_description:'Music and podcasts with playlists, discovery and offline listening features.',developer:'Spotify AB',version:'9.0.48',android_required:'8.0+',size:'89 MB',rating:4.8,downloads:1000000000,category_id:5,category:demoCategories[4],icon_url:icon('spotify'),brand_color:'#1DB954',apk_url:'#demo-download',mod_info:'Premium-style demo listing',status:'published',featured:true,trending:true,app_type:'app',features:['Music & podcasts','Personal playlists','Offline-ready listing','High quality audio'],specifications:[{label:'Version',value:'9.0.48'},{label:'Android',value:'8.0+'},{label:'Size',value:'89 MB'}],content_html:commonContent('Spotify'),seo_title:'Spotify APK - Latest Version',meta_description:'Spotify Android app demo listing.'},
  {id:2,title:'YouTube',slug:'youtube',short_description:'Watch videos, channels, creators and personalised recommendations on Android.',developer:'Google LLC',version:'21.31.36',android_required:'8.0+',size:'152 MB',rating:4.7,downloads:5000000000,category_id:1,category:demoCategories[0],icon_url:icon('youtube'),brand_color:'#FF0000',apk_url:'#demo-download',mod_info:'Demo listing',status:'published',featured:true,trending:true,app_type:'app',features:['Video streaming','Subscriptions','Playlists','Creator channels'],specifications:[{label:'Version',value:'21.31.36'},{label:'Android',value:'8.0+'},{label:'Size',value:'152 MB'}],content_html:commonContent('YouTube'),seo_title:'YouTube APK - Latest Version',meta_description:'YouTube Android app demo listing.'},
  {id:3,title:'WhatsApp',slug:'whatsapp',short_description:'Private messaging, voice calls, video calls and group conversations.',developer:'WhatsApp LLC',version:'2.26.22',android_required:'6.0+',size:'82 MB',rating:4.8,downloads:5000000000,category_id:6,category:demoCategories[5],icon_url:icon('whatsapp'),brand_color:'#25D366',apk_url:'#demo-download',mod_info:'Demo listing',status:'published',featured:true,trending:true,app_type:'app',features:['Private chats','Voice & video calls','Groups','Media sharing'],specifications:[{label:'Version',value:'2.26.22'},{label:'Android',value:'6.0+'},{label:'Size',value:'82 MB'}],content_html:commonContent('WhatsApp'),seo_title:'WhatsApp APK - Latest Version',meta_description:'WhatsApp Android app demo listing.'},
  {id:4,title:'Telegram',slug:'telegram',short_description:'Fast cloud messaging with channels, large groups and media sharing.',developer:'Telegram FZ-LLC',version:'12.1.2',android_required:'6.0+',size:'78 MB',rating:4.7,downloads:1000000000,category_id:6,category:demoCategories[5],icon_url:icon('telegram'),brand_color:'#26A5E4',apk_url:'#demo-download',mod_info:'Demo listing',status:'published',featured:true,trending:false,app_type:'app',features:['Cloud chats','Channels','Large groups','File sharing'],specifications:[{label:'Version',value:'12.1.2'},{label:'Android',value:'6.0+'},{label:'Size',value:'78 MB'}],content_html:commonContent('Telegram'),seo_title:'Telegram APK - Latest Version',meta_description:'Telegram Android app demo listing.'},
  {id:5,title:'Netflix',slug:'netflix',short_description:'Movies, series and entertainment streaming with personalised profiles.',developer:'Netflix, Inc.',version:'9.36.0',android_required:'8.0+',size:'98 MB',rating:4.6,downloads:1000000000,category_id:1,category:demoCategories[0],icon_url:icon('netflix'),brand_color:'#E50914',apk_url:'#demo-download',mod_info:'Demo listing',status:'published',featured:false,trending:true,app_type:'app',features:['Movies & series','Profiles','Watchlist','Offline downloads'],specifications:[{label:'Version',value:'9.36.0'},{label:'Android',value:'8.0+'},{label:'Size',value:'98 MB'}],content_html:commonContent('Netflix'),seo_title:'Netflix APK - Latest Version',meta_description:'Netflix Android app demo listing.'},
  {id:6,title:'TikTok',slug:'tiktok',short_description:'Short-form video, creators, trends, music and personalised discovery.',developer:'TikTok Pte. Ltd.',version:'41.2.4',android_required:'6.0+',size:'136 MB',rating:4.7,downloads:1000000000,category_id:7,category:demoCategories[6],icon_url:icon('tiktok'),brand_color:'#111111',apk_url:'#demo-download',mod_info:'Demo listing',status:'published',featured:false,trending:true,app_type:'app',features:['Short videos','Creator tools','Music & trends','Personal feed'],specifications:[{label:'Version',value:'41.2.4'},{label:'Android',value:'6.0+'},{label:'Size',value:'136 MB'}],content_html:commonContent('TikTok'),seo_title:'TikTok APK - Latest Version',meta_description:'TikTok Android app demo listing.'},
  {id:7,title:'Discord',slug:'discord',short_description:'Communities, chat, voice channels and gaming conversations in one place.',developer:'Discord Inc.',version:'293.12',android_required:'7.0+',size:'118 MB',rating:4.6,downloads:500000000,category_id:6,category:demoCategories[5],icon_url:icon('discord'),brand_color:'#5865F2',apk_url:'#demo-download',mod_info:'Demo listing',status:'published',featured:false,trending:true,app_type:'app',features:['Servers','Voice channels','Communities','Direct messages'],specifications:[{label:'Version',value:'293.12'},{label:'Android',value:'7.0+'},{label:'Size',value:'118 MB'}],content_html:commonContent('Discord'),seo_title:'Discord APK - Latest Version',meta_description:'Discord Android app demo listing.'},
  {id:8,title:'CapCut',slug:'capcut',short_description:'Mobile video editing with templates, effects, transitions and creator tools.',developer:'Bytedance Pte. Ltd.',version:'15.2.0',android_required:'6.0+',size:'154 MB',rating:4.8,downloads:1000000000,category_id:4,category:demoCategories[3],icon_url:icon('capcut'),brand_color:'#111111',apk_url:'#demo-download',mod_info:'Pro-style demo listing',status:'published',featured:true,trending:true,app_type:'app',features:['Video editor','Templates','Transitions','Creator tools'],specifications:[{label:'Version',value:'15.2.0'},{label:'Android',value:'6.0+'},{label:'Size',value:'154 MB'}],content_html:commonContent('CapCut'),seo_title:'CapCut APK - Latest Version',meta_description:'CapCut Android app demo listing.'},
  {id:9,title:'Pinterest',slug:'pinterest',short_description:'Discover ideas, inspiration, collections and visual content for every interest.',developer:'Pinterest',version:'13.31.0',android_required:'8.0+',size:'74 MB',rating:4.7,downloads:500000000,category_id:7,category:demoCategories[6],icon_url:icon('pinterest'),brand_color:'#E60023',apk_url:'#demo-download',mod_info:'Demo listing',status:'published',featured:false,trending:false,app_type:'app',features:['Visual discovery','Boards','Collections','Idea search'],specifications:[{label:'Version',value:'13.31.0'},{label:'Android',value:'8.0+'},{label:'Size',value:'74 MB'}],content_html:commonContent('Pinterest'),seo_title:'Pinterest APK - Latest Version',meta_description:'Pinterest Android app demo listing.'},
  {id:10,title:'Reddit',slug:'reddit',short_description:'Communities, conversations, news, entertainment and interest-based feeds.',developer:'Reddit Inc.',version:'2026.31.0',android_required:'8.0+',size:'106 MB',rating:4.6,downloads:500000000,category_id:7,category:demoCategories[6],icon_url:icon('reddit'),brand_color:'#FF4500',apk_url:'#demo-download',mod_info:'Demo listing',status:'published',featured:false,trending:false,app_type:'app',features:['Communities','Discussion threads','Custom feeds','Saved posts'],specifications:[{label:'Version',value:'2026.31.0'},{label:'Android',value:'8.0+'},{label:'Size',value:'106 MB'}],content_html:commonContent('Reddit'),seo_title:'Reddit APK - Latest Version',meta_description:'Reddit Android app demo listing.'},
  {id:11,title:'Roblox',slug:'roblox',short_description:'Explore user-created experiences, worlds and multiplayer games on Android.',developer:'Roblox Corporation',version:'2.687',android_required:'6.0+',size:'186 MB',rating:4.7,downloads:1000000000,category_id:3,category:demoCategories[2],icon_url:icon('roblox'),brand_color:'#111111',apk_url:'#demo-download',mod_info:'Demo game listing',status:'published',featured:true,trending:true,app_type:'game',features:['Multiplayer worlds','Avatar customisation','User-created games','Cross-platform play'],specifications:[{label:'Version',value:'2.687'},{label:'Android',value:'6.0+'},{label:'Size',value:'186 MB'}],content_html:commonContent('Roblox'),seo_title:'Roblox APK - Latest Version',meta_description:'Roblox Android game demo listing.'},
  {id:12,title:'Steam',slug:'steam',short_description:'Browse games, manage your library and stay connected to the Steam community.',developer:'Valve Corporation',version:'3.10.5',android_required:'7.0+',size:'46 MB',rating:4.6,downloads:100000000,category_id:3,category:demoCategories[2],icon_url:icon('steam'),brand_color:'#171A21',apk_url:'#demo-download',mod_info:'Demo game companion listing',status:'published',featured:false,trending:false,app_type:'game',features:['Game library','Store browsing','Community','Steam Guard'],specifications:[{label:'Version',value:'3.10.5'},{label:'Android',value:'7.0+'},{label:'Size',value:'46 MB'}],content_html:commonContent('Steam'),seo_title:'Steam APK - Latest Version',meta_description:'Steam Android app demo listing.'}
];

export const demoPages = {
  'about-us': { title: 'About Us', slug:'about-us', content_html:'<h2>About APKMarket</h2><p>APKMarket is an Android app directory. Manage this page from your CMS.</p>' },
  'privacy-policy': { title:'Privacy Policy', slug:'privacy-policy', content_html:'<h2>Privacy Policy</h2><p>Add your final privacy policy here before launch.</p>' },
  'terms': { title:'Terms & Conditions', slug:'terms', content_html:'<h2>Terms & Conditions</h2><p>Add your final legal terms here before launch.</p>' },
  'dmca': { title:'DMCA / Copyright', slug:'dmca', content_html:'<h2>Copyright & Takedowns</h2><p>Provide a clear process for rights holders to report content.</p>' },
  'disclaimer': { title:'Disclaimer', slug:'disclaimer', content_html:'<h2>Disclaimer</h2><p>Only host or link to software you are authorised to distribute. Review files for security before publishing.</p>' }
};
