import Header from '@/components/Header';import Footer from '@/components/Footer';import Section from '@/components/Section';import {getAppBySlug,getApps} from '@/lib/db';import {notFound} from 'next/navigation';
export const dynamic='force-dynamic';
function compact(n=0){return n>=1e9?`${(n/1e9).toFixed(1)}B`:n>=1e6?`${(n/1e6).toFixed(1)}M`:n>=1e3?`${Math.round(n/1e3)}K`:String(n)}
export async function generateMetadata({params}){const {slug}=await params;const a=await getAppBySlug(slug);if(!a)return{};return{title:a.seo_title||a.title,description:a.meta_description||a.short_description,alternates:a.canonical_url?{canonical:a.canonical_url}:undefined,robots:a.robots||'index,follow'};}
export default async function Page({params}){const{slug}=await params;const app=await getAppBySlug(slug);if(!app||app.status!=='published')notFound();const related=(await getApps({categorySlug:app.category?.slug,limit:5})).filter(a=>a.id!==app.id).slice(0,4);let schema=app.schema_json;if(!schema){schema={"@context":"https://schema.org","@type":"SoftwareApplication",name:app.title,applicationCategory:app.category?.name||'AndroidApplication',operatingSystem:`Android ${app.android_required||''}`,description:app.short_description,aggregateRating:app.rating?{"@type":"AggregateRating",ratingValue:app.rating,ratingCount:Math.max(1,Math.round((app.downloads||1)/100))}:undefined};}
return <><Header/><main className="container app-page">{schema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>}
  <div className="breadcrumbs"><a href="/">Home</a><span>›</span><a href={app.category?.slug?`/category/${app.category.slug}`:'/apps'}>{app.category?.name||'Apps'}</a><span>›</span><b>{app.title}</b></div>
  <section className="app-hero-card"><div className="detail-icon" style={app.brand_color?{background:app.brand_color}:undefined}><img src={app.icon_url||'/demo/icons/default.svg'} alt={`${app.title} icon`}/></div><div className="detail-copy"><div className="detail-tags"><span>{app.app_type==='game'?'GAME':'APP'}</span>{app.mod_info&&<span className="green-tag">MOD</span>}</div><h1>{app.title}</h1><p className="developer">{app.developer} · {app.category?.name}</p><p className="detail-description">{app.short_description}</p><div className="detail-stats"><div><strong>★ {Number(app.rating||0).toFixed(1)}</strong><small>Rating</small></div><div><strong>{compact(app.downloads)}+</strong><small>Downloads</small></div><div><strong>{app.version||'Latest'}</strong><small>Version</small></div><div><strong>{app.size||'—'}</strong><small>Size</small></div></div></div><div className="detail-action"><a className="download-btn" href={app.apk_url||'#'} rel="nofollow">Download APK <span>↓</span></a><small>Android {app.android_required||'compatible'}</small></div></section>
  <div className="detail-layout"><article className="article-card">{app.screenshots?.length>0&&<div className="screenshot-gallery">{app.screenshots.map((url,i)=><img key={i} src={url} alt={`${app.title} screenshot ${i+1}`}/>)}</div>}{app.mod_info&&<div className="release-note"><span>MOD / RELEASE</span><p>{app.mod_info}</p></div>}<div className="rich-content" dangerouslySetInnerHTML={{__html:app.content_html||''}}/></article><aside className="detail-sidebar"><div className="side-card"><h3>App information</h3><table className="spec-table"><tbody><tr><td>Version</td><td>{app.version||'—'}</td></tr><tr><td>Android</td><td>{app.android_required||'—'}</td></tr><tr><td>Size</td><td>{app.size||'—'}</td></tr><tr><td>Developer</td><td>{app.developer||'—'}</td></tr>{(app.specifications||[]).map((s,i)=><tr key={i}><td>{s.label}</td><td>{s.value}</td></tr>)}</tbody></table></div>{app.features?.length>0&&<div className="side-card"><h3>Highlights</h3><ul className="feature-list">{app.features.map((f,i)=><li key={i}><span>✓</span>{f}</li>)}</ul></div>}</aside></div>
  <Section title="You may also like" subtitle={`More from ${app.category?.name||'this category'}`} apps={related}/>
</main><Footer/></>}
